Sites registration
AgID/wai-user-guide-docs pull request #1
Opened 2019-11-25 15:53 UTC by Valair

2019-11-25 17:19 UTC, pdavide requested changes

2019-11-25 17:19 UTC, pdavide commented on registrazione-sito-primario-pubblica-amministrazione/inserimento-sito-primario.rst
> +|image0|
Le figura vanno inserite usando la sintassi prevista dalla guida: https://docs.italia.it/italia/docs-italia/docs-italia-guide/it/bozza/appendice-2/figure.html

2019-11-25 17:19 UTC, pdavide commented on registrazione-sito-primario-pubblica-amministrazione/inserimento-sito-primario.rst
> +|image1|
Le figura vanno inserite usando la sintassi prevista dalla guida: https://docs.italia.it/italia/docs-italia/docs-italia-guide/it/bozza/appendice-2/figure.html

2019-11-25 17:19 UTC, pdavide commented on document_settings.yml
> +  name: Linee Guida Web Analytics Italia
```suggestion
  name: Guida utente di Web Analytics Italia
```

2019-11-25 17:19 UTC, pdavide commented on document_settings.yml
> +      Linee Guida Web Analytics Italia
```suggestion
      La guida utente di Web Analytics Italia spiega le principali procedure di utilizzo della piattaforma.
```

2019-11-25 17:19 UTC, pdavide commented on document_settings.yml
> +    - Sito Primario PA
```suggestion
    - WAI
    - Web Analytics Italia
    - Statistiche
    - Guida utente
```

2019-11-25 17:19 UTC, pdavide commented on document_settings.yml
> +    - linee guida
```suggestion

```

2019-11-25 17:19 UTC, pdavide commented on index.rst
> +**Registrazione sito primario PA**
```suggestion
Guida utente di Web Analytics Italia
====================================
```

2019-11-25 17:19 UTC, pdavide commented on index.rst
> +  :caption: Indice dei contenuti
```suggestion
```

2019-11-25 17:19 UTC, pdavide commented on index.rst
> +  sommario.rst
Una elenco dei contenuti è già generato dalla direttiva `toctree`. Un breve sommario (nel senso di summary - riassunto) è opportuno all'inizio di ogni capitolo. Vedi: https://docs.italia.it/italia/docs-italia/docs-italia-guide/it/bozza/appendice-2/riassunto.html

2019-11-25 17:19 UTC, pdavide commented on registrazione-sito-primario-pubblica-amministrazione.rst
> +**Registrazione sito primario Pubblica amministrazione**
```suggestion
Registrazione sito primario Pubblica amministrazione
```
I titoli non vanno formattati esplicitamente in grassetto.

2019-11-25 17:19 UTC, pdavide commented on registrazione-sito-primario-pubblica-amministrazione.rst
> +========================================================
```suggestion
========================================================
---------------------------------------------------------
```
https://docs.italia.it/italia/docs-italia/docs-italia-guide/it/bozza/appendice-2/titoli.html

2019-11-25 17:19 UTC, pdavide commented on registrazione-sito-primario-pubblica-amministrazione.rst
> +.. toctree::
Qui eviterei di creare un ulteriore livello di navigazione, invece suggerirei di inserire il testo direttamente in questo file rispettando le convenzioni per i titoli di sezioni e sotto-sezioni => https://docs.italia.it/italia/docs-italia/docs-italia-guide/it/bozza/appendice-2/titoli.html

2019-11-25 19:17 UTC, Valair commented
Coinvolgo @acampone che si sta occupando della realizzazione degli articoli

2019-11-27 15:46 UTC, pdavide requested changes

2019-11-27 15:46 UTC, pdavide commented on registrazione-sito-primario-pubblica-amministrazione.rst
> +**Attività propedeutiche**
```suggestion
Attività propedeutiche
```
I titoli di sezione non richiedono il grassetto.

2019-11-27 15:46 UTC, pdavide commented on registrazione-sito-primario-pubblica-amministrazione.rst
> +**Inserimento sito primario**
```suggestion
Inserimento sito primario
```
I titoli di sezione non richiedono il grassetto.

2019-11-27 15:46 UTC, pdavide commented on registrazione-sito-primario-pubblica-amministrazione.rst
> +E’ previsto come dato propedeutico anche che l’utente abbia
```suggestion
È previsto come dato propedeutico anche che l’utente abbia
```

2019-11-27 15:48 UTC, danielaiozzo requested changes

2019-11-27 15:48 UTC, danielaiozzo commented on registrazione-sito-primario-pubblica-amministrazione/attività-propedeutiche.rst
> +   registrata una mail di posta elettronica
registrata dove? si intende che l'utente abbia un account di posta elettronica attivo?

2019-11-27 15:48 UTC, danielaiozzo commented on registrazione-sito-primario-pubblica-amministrazione/inserimento-sito-primario.rst
> +   della registrazione, l’utente sarà posizionato in automatico nella
```suggestion
   della registrazione, l’utente sarà direzionato automaticamente alla
```

2019-11-27 15:48 UTC, danielaiozzo commented on registrazione-sito-primario-pubblica-amministrazione/inserimento-sito-primario.rst
> +   visualizzati. Nel caso in cui i dati sia corretti l’utente dovrà
```suggestion
   visualizzati. Nel caso in cui i dati siano corretti l’utente dovrà
```

2019-11-27 15:48 UTC, danielaiozzo commented on registrazione-sito-primario-pubblica-amministrazione/inserimento-sito-primario.rst
> +   mostrato all’utente messaggio di conferma di avvenuto inserito
```suggestion
   mostrato all’utente messaggio di conferma di avvenuto inserimento
```

2019-11-27 15:48 UTC, danielaiozzo commented on registrazione-sito-primario-pubblica-amministrazione.rst
> +**Registrazione sito primario Pubblica amministrazione**
```suggestion
**Registrazione sito istituzionale Pubblica amministrazione**
```

2019-11-27 15:48 UTC, danielaiozzo commented on registrazione-sito-primario-pubblica-amministrazione/inserimento-sito-primario.rst
> +   Amministrazione di interesse saranno mostrati precaricati e non
```suggestion
   Amministrazione  saranno mostrati precaricati e non
```

2019-11-28 15:41 UTC, Valair commented
Come da indicazioni slack, rimosse referenze al sito istituzionale e tolte le dissolvenze al video

2019-12-09 16:03 UTC, pdavide approved these changes

2019-12-09 16:04 UTC, merged

2019-12-09 17:16 UTC, danielaiozzo commented on siti/archiviazione.rst
> +Archiviazione manuale sito secondario
```suggestion
Archiviazione manuale sito secondario
```
```suggestion
Archiviazione manuale di un sito secondario
```

2019-12-09 17:16 UTC, danielaiozzo commented on siti/archiviazione.rst
> +   Descrizione dei passi necessari per archiviare un sito secondario della PA.
```suggestion
   Descrizione dei passi necessari per archiviare un sito secondario della PA.
```
```suggestion
Come archiviare un sito secondario della tua PA.
```

2019-12-09 17:16 UTC, danielaiozzo commented on siti/archiviazione.rst
> +Effettuato l’accesso al sistema, nel Tab
```suggestion
Effettuato l’accesso al sistema, nel Tab
```
```suggestion
Ad accesso effettuato, nel Tab
```

2019-12-09 17:16 UTC, danielaiozzo commented on siti/archiviazione.rst
> +**Siti Web** viene mostrato
```suggestion
**Siti Web** puoi visualizzare
```

2019-12-09 17:16 UTC, danielaiozzo commented on siti/archiviazione.rst
> +l’elenco dei siti della PA già presenti.
```suggestion
l’elenco dei siti della PA già presenti.
```
```suggestion
l’elenco dei siti della tua PA già presenti.
```

2019-12-09 17:16 UTC, danielaiozzo commented on siti/archiviazione.rst
> +L'operazione di archiviazione, disponibile solo per i siti in stato *Attivo*,
```suggestion
Puoi effettuare l'operazione di archiviazione, disponibile solo per i siti in stato *Attivo*,
```

2019-12-09 17:16 UTC, danielaiozzo commented on siti/archiviazione.rst
> +può essere effettuata in una delle seguenti modalità:
```suggestion
 in una delle seguenti modalità:
```

2019-12-09 17:16 UTC, danielaiozzo commented on siti/archiviazione.rst
> +Riattivazione manuale sito secondario
```suggestion
Riattivazione manuale sito secondario
```
```suggestion
Riattivazione manuale di un sito secondario
```

2019-12-09 17:16 UTC, danielaiozzo commented on siti/archiviazione.rst
> +   Descrizione dei passi necessari per riattivare un sito secondario della PA.
```suggestion
   Come riattivare un sito secondario della tua PA.
```

2019-12-09 17:16 UTC, danielaiozzo commented on siti/archiviazione.rst
> +Effettuato l’accesso al sistema, nel Tab
```suggestion
Ad accesso effettuato, nel Tab
```

2019-12-09 17:16 UTC, danielaiozzo commented on siti/archiviazione.rst
> +**Siti Web** viene mostrato
```suggestion
**Siti Web** puoi visualizzare
```

2019-12-09 17:16 UTC, danielaiozzo commented on siti/archiviazione.rst
> +l’elenco dei siti della PA già presenti.
```suggestion
l’elenco dei siti della tua PA già presenti.
```

2019-12-09 17:16 UTC, danielaiozzo commented on siti/archiviazione.rst
> +L'operazione di riattivazione, disponibile
```suggestion
Puoi effettuare l'operazione di riattivazione, disponibile
```

2019-12-09 17:16 UTC, danielaiozzo commented on siti/archiviazione.rst
> +può essere effettuata in una delle seguenti modalità:
```suggestion
 in una delle seguenti modalità:
```

2019-12-09 17:16 UTC, danielaiozzo commented on siti/archiviazione.rst
> +- Utilizzando il pulsante con etichetta *riattiva*
```suggestion
- Utilizzando il pulsante *riattiva*
```

2019-12-09 17:16 UTC, danielaiozzo commented on siti/archiviazione.rst
> +Nell'elenco dei siti, lo stato sarà aggiornato a *attivo*.
```suggestion
Nell'elenco dei siti, lo stato del sito riattivato sarà aggiornato a *attivo*.
```

2019-12-09 17:16 UTC, danielaiozzo commented on siti/archiviazione.rst
> +  il pulsante *dettagli*, quindi all'interno della sezione **STATO**,
```suggestion
 all'interno della sezione *dettagli* e poi **STATO**,
```

2019-12-09 17:16 UTC, danielaiozzo commented on siti/archiviazione.rst
> +- Entrando nella schermata di dettaglio del sito, usando
```suggestion
- Nella schermata di dettaglio del sito, 
```

2019-12-09 17:16 UTC, danielaiozzo commented on siti/index.rst
> +Gestione siti secondari Pubblica Amministrazione
```suggestion
Gestione dei siti tematici della Pubblica Amministrazione
```

2019-12-09 17:16 UTC, danielaiozzo commented on siti/archiviazione.rst
> +Archiviazione manuale sito secondario
@valair ovunque occorre sostituire la locuzione "sito secondario" con "sito tematico"

2019-12-09 17:16 UTC, danielaiozzo commented on siti/inserimento.rst
> +Gestione sito secondario Pubblica Amministrazione
```suggestion
Gestione di un sito tematico della Pubblica Amministrazione
```

2019-12-09 17:16 UTC, danielaiozzo commented on siti/inserimento.rst
> +   Descrizione dei passi necessari per la registrazione del sito secondario di una Pubblica Amministrazione sul portale Web Analytics Italia.
```suggestion
Come registrare il sito tematico di una Pubblica Amministrazione sul portale Web Analytics Italia.
```

2019-12-09 17:16 UTC, danielaiozzo commented on siti/inserimento.rst
> +Inserimento sito secondario
```suggestion
Come inserire un sito tematico
```

2019-12-09 17:17 UTC, danielaiozzo reviewed
@Valair la review è incompleta. ne parliamo quanto prima

2019-12-09 21:07 UTC, Valair commented on siti/archiviazione.rst
> +Archiviazione manuale sito secondario
@danielaiozzo su portale `tematico` (per la precisione `informativo o tematico`) è una delle tre tipologie che si possono scegliere per i siti non istituzionali; non sarebbe fuorviante? oppure è prevista una modifica della nomenclatura sul portale?

2019-12-09 21:16 UTC, Valair commented on siti/index.rst
> +Gestione siti secondari Pubblica Amministrazione
@danielaiozzo vedi commento sopra

2019-12-09 21:16 UTC, Valair commented on siti/inserimento.rst
> +Gestione sito secondario Pubblica Amministrazione
@danielaiozzo vedi commento sopra