Add pa dashboard article
AgID/wai-user-guide-docs pull request #10
Opened 2020-02-03 09:30 UTC by Valair

2020-02-03 10:48 UTC, danielaiozzo requested changes

2020-02-03 10:48 UTC, danielaiozzo commented on pa_dashboard/index.rst
> +Informazioni sulla dashboard privata delle Pubbliche Amministrazioni
Non si era detto di chiamarla "I tuoi dati"? @Valair @pdavide

2020-02-03 10:48 UTC, danielaiozzo commented on pa_dashboard/index.rst
> +Accedendo al portale, nella pagina degli "Analytics"
```suggestion
Quando accedi a WAI nella sezione dedicata agli "Analytics"
```

2020-02-03 10:48 UTC, danielaiozzo commented on pa_dashboard/index.rst
> +puoi visualizzare una panoramica sui siti web
```suggestion
puoi visualizzare la panoramica dei siti
```

2020-02-03 10:48 UTC, danielaiozzo commented on pa_dashboard/index.rst
> +Le informazioni visualizzate in questa pagina
```suggestion
Le informazioni visualizzate in questa pagina
```
```suggestion
Le informazioni visualizzate in questa sezione
```

2020-02-03 10:48 UTC, danielaiozzo commented on pa_dashboard/index.rst
> +nei trenta giorni antecedenti.
```suggestion
nei trenta giorni precedenti la data di consultazione. 
```

2020-02-03 10:48 UTC, danielaiozzo commented on pa_dashboard/index.rst
> +poiché riportanto indicazioni generiche di ampia utilità,
```suggestion
poiché riportano dati aggregati in base ai KPI (indicatori) di web analytics più comuni
```

2020-02-03 10:48 UTC, danielaiozzo commented on pa_dashboard/index.rst
> +Se invece vuoi vedere altri indicatori, esaminare
```suggestion
Se invece vuoi visualizzare ulteriori indicatori, esaminare
```

2020-02-03 10:48 UTC, danielaiozzo commented on pa_dashboard/index.rst
> +i dati per uno specifico sito web o un diverso
```suggestion
i dati di un singolo sito web oppure ripetere l'elaborazione sulla base di un diverso
```

2020-02-03 11:17 UTC, Valair commented on pa_dashboard/index.rst
> +Accedendo al portale, nella pagina degli "Analytics"
Ho evitato di chiamare questa pagina come "sezione" per evitare di creare confusione con la "sezione analytics" che è il nome che abbiamo dato nell'[altro articolo](https://github.com/AgID/wai-user-guide-docs/blob/matomo_dashboard/analytics_dashboard/index.rst) alla dashboard di matomo.

2020-02-03 11:18 UTC, Valair commented on pa_dashboard/index.rst
> +Informazioni sulla dashboard privata delle Pubbliche Amministrazioni
Su portale la pagina è "Analytics", ma (vedi https://github.com/AgID/wai-user-guide-docs/pull/10#discussion_r374047263) non volevo creare confusione ed ho scelto questo nome.

2020-02-03 11:19 UTC, Valair commented on pa_dashboard/index.rst
> +Le informazioni visualizzate in questa pagina
Come sopra

2020-02-03 11:23 UTC, danielaiozzo commented on pa_dashboard/index.rst
> +Accedendo al portale, nella pagina degli "Analytics"
ok allora mantieni "pagina"

2020-02-03 18:38 UTC, Valair commented
Ho applicato le correzioni, ma rimane aperta la questione del nome della pagina.

2020-02-03 19:06 UTC, danielaiozzo commented
Ok. Magari ne discutiamo domani nel SAL

Il giorno Lun 3 Feb 2020 19:38 Andrea Capelli <notifications@github.com> ha
scritto:

> Ho applicato le correzioni, ma rimane aperta la questione del nome della
> pagina.
>
> —
> You are receiving this because your review was requested.
> Reply to this email directly, view it on GitHub
> <https://github.com/AgID/wai-user-guide-docs/pull/10?email_source=notifications&email_token=ADVB7DWG5N3YFY56C6I4WZTRBBQBBA5CNFSM4KPBZZ3KYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEKU5JYI#issuecomment-581555425>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ADVB7DXV4JIWEAOA3KSGGS3RBBQBBANCNFSM4KPBZZ3A>
> .
>

2020-02-11 16:34 UTC, pdavide approved these changes

2020-02-11 16:35 UTC, merged