Add public dashboard articles
AgID/wai-user-guide-docs pull request #9
Opened 2020-02-03 09:29 UTC by Valair

2020-02-03 10:38 UTC, danielaiozzo requested changes

2020-02-03 10:38 UTC, danielaiozzo commented on public_dashboard/index.rst
> +   Cosa mostra la dashboard pubblica del portale
```suggestion
   Cosa mostra la dashboard pubblica di WAI
```

2020-02-03 10:38 UTC, danielaiozzo commented on public_dashboard/index.rst
> +I dati provenienti dai siti web presenti nel portale
```suggestion
I dati provengono dai siti web in quel momento presenti nel portale
```

2020-02-03 10:38 UTC, danielaiozzo commented on public_dashboard/index.rst
> +che hanno superato la fase di attivazione, sono
```suggestion
e che hanno superato la fase di attivazione. I dati sono
```

2020-02-03 10:38 UTC, danielaiozzo commented on public_dashboard/index.rst
> +aggregati ed elaborati per estrarre informazioni
```suggestion
aggregati ed elaborati per estrarre informazioni
```
```suggestion
aggregati ed elaborati per mostrare informazioni
```

2020-02-03 10:38 UTC, danielaiozzo commented on public_dashboard/index.rst
> +  la loro durata, la velocità di risposta o le ricerche
```suggestion
  la loro durata, la velocità di risposta o le ricerche
```
```suggestion
  la loro durata, la velocità di caricamento delle pagine o le ricerche
```

2020-02-03 10:38 UTC, danielaiozzo commented on public_dashboard/index.rst
> +Infine, puoi vedere quante pubbliche amministrazioni
```suggestion
Infine, puoi vedere in tempo reale quante pubbliche amministrazioni
```

2020-02-03 10:38 UTC, danielaiozzo commented on public_dashboard/index.rst
> +hanno aderito al progetto e quanti dei loro siti web sono
```suggestion
hanno aderito al progetto e quanti siti web 
```

2020-02-03 10:38 UTC, danielaiozzo commented on public_dashboard/index.rst
> +collaborano attivamente alla fornitura delle informazioni.
```suggestion
stanno attivamente contribuendo alla valorizzazione dei dati nei widget della dashboard.
```

2020-02-03 10:38 UTC, danielaiozzo commented on public_dashboard/index.rst
> +- valutare la qualità e la fruibilità dei siti stessi,
```suggestion
- la qualità e la fruibilità dei siti stessi,
```

2020-02-03 10:38 UTC, danielaiozzo commented on public_dashboard/index.rst
> +  a partire da semplici indicatori come la quantità di visite,
```suggestion
  valutabili a partire da semplici indicatori come la quantità di visite,
```

2020-02-11 16:33 UTC, pdavide approved these changes

2020-02-11 16:34 UTC, merged